service: aws-odtr-node

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  role: arn:aws:iam::491150663186:role/service-role/basic.execution
  memorySize: 128
  timeout: 5

functions:
  aws_odtr:
    handler: handler.main
    name: aws-odtr
    description: Login automation
    environment:
      DEBUG: true
      DEPLOY: true
      BUCKET: janmir
      FILE: schema.yaml
    tags:
      type: work
  
package:
  exclude:
    - schema.yaml
    - README.md
    - event.json